# -*- coding: utf-8 -*-
"""escapechara.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KNzORM_Zt6cHMjH37FkxrPLhPaa5sbeL
"""

print ('"Dia berkata : "Kesini"')

print (" aku menimpali : \"apakah kau ingin aku 'angkat kaki'?!\" ")

print (" \\(>_<)/ (\\-_-) ")