# -*- coding: utf-8 -*-
"""Penggabungan String.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13N2jWgy3rbDnBgTkgZJ8WeMDVs6rwTsj

**string**
"""

nama = "rahmasari rahayu"
asal = "Indo"

print(nama)

print(asal)

print (nama, asal)

print (nama + asal)

print ('halo, nama saya',nama)

print ('halo, nama saya',nama,'asal saya dari', asal)

data_lengkap = nama + asal

print(data_lengkap)

data_lengkap = nama + asal

"""**string+no string**"""

asal_kota = "bandar lampunk"
kode_pos = 351141

asal_kota_kode_pos = asal_kota + str(kode_pos)
print(asal_kota_kode_pos)

asal_kota_x3 = asal_kota * 3
print(asal_kota_x3)